### ISSUE TITLE
can it use fetch robot?

### ISSUE THREAD

**Issue by Bailey-24** [eric-ai-lab/VLMbench#8]
I want  to sim2real in fetch robot, can the benchmark use the fetch robot?

**Comment by KzZheng** [comment]
Sorry for the late reply. Since we use [PyRep](https://github.com/stepjam/PyRep/tree/master) as our backend, I think it is possible to add [robot arms](https://github.com/stepjam/PyRep#supported-robots) and [new robots](https://github.com/stepjam/PyRep#adding-robots). Please check their repo for more details.
